### ISSUE TITLE
YAML

### ISSUE THREAD

**Issue by devcurmudgeon** [GENIVI/vehicle_signal_specification#2]
Would you consider adopting YAML, rather than JSON, as the default format for the structured data? In general I think humans find yaml easier to read, and computers are happy with either. 

Also, would it make sense to consider establishing a schema for this early on, so that the schema can be used to validate actual files (eg http://json-schema.org)? And versioning of the schema?

**Comment by magnusfeuer** [comment]
Given that YAML is a full-blown IDL (much like Franca), it is, IMHO, overkill to use it to describe a vehicle signal spec, and would provide a higher barrier of entry than hated-but-known JSON.

As for schema, absolutely. I was going to do all the validation in a vss_parser.py script but a JSON-schema is also a very viable path forward. I'll see how I can roll that into the mix.

All tools will end up in the vehicle_signal_tools repo so that we can separate spec releases from tools releases.
