### ISSUE TITLE
Inconsistency "datatype" definition in json

### ISSUE THREAD

**Issue by phongt** [GENIVI/vehicle_signal_specification#210]
curl https://genivi.github.io/vehicle_signal_specification/releases/nightly/vss_rel_2.0.0-alpha+006.json | grep datatype | sed "s/^[ \t]*//" | sort | uniq

```
"datatype": "boolean",
"datatype": "Double",
"datatype": "float",
"datatype": "Float",
"datatype": "int16",
"datatype": "Int16",
"datatype": "int32",
"datatype": "int8",
"datatype": "Int8",
"datatype": "string",
"datatype": "string[]",
"datatype": "uint16",
"datatype": "UInt16",
"datatype": "uint32",
"datatype": "Uint32",
"datatype": "uint8",
"datatype": "uint8[]",
"datatype": "UInt8",
```

Some with upper case and some in lower case. In the documentation [Vehicle Signal Specification > Rule Set > Data Entry > Data Types](https://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/data_types/). 
IMO, it shall be unification.

**Comment by SebastianSchildt** [comment]
Good catch! e.g. "Float" in Powertrain.BatteryBattery.StateOfCharge or UInt32 in Powertrain.ElectriMotor.Motor.Rpm

Some of those are even recent additions :(  

@danielwilms: Shouldn't our "new" tooling via Travis catch this? Definitely should make it consistent before tagging 2.0

Also I noticed the table https://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/data_types/ gives upper case, but the vast majority of the units (and in examples) is lower case. So I suggest the fix is: All lowercase
