### ISSUE TITLE
doc: Incorrect paths in tools/vss_documentation/

### ISSUE THREAD

**Issue by slawr** [GENIVI/vehicle_signal_specification#278]
The opening paragraph of the documentation page at https://genivi.github.io/vehicle_signal_specification/tools/vss_documentation/ states:
_The VSS documentation is realized with GitHub Pages. It is generated from the markdown files in the /documentation directory of this repositories. The static webpage is generated into the /docs directory so that it can be deployed straight from the repository._

I may be missing something related to the documentation generation, but at first sight the two directories that are referenced do not appear to be in the github sources. Being unfamiliar with the generation process I am raising an issue as a first step.

Update: reading further the paths in the "Contribution" section at the bottom of the page may also be wrong.

**Comment by gunnarx** [comment]
Agreed.  It seems it is the directory named [docs-gen](https://github.com/GENIVI/vehicle_signal_specification/tree/master/docs-gen) for the source files, and instead of generating the results into a particular directory, it is stored on the [gh-pages](https://github.com/GENIVI/vehicle_signal_specification/tree/gh-pages) branch (which is a GitHub convention to create GitHub Pages)
